### ISSUE TITLE
BulkInsertIntoTempTableAsync doesn't use PropertiesToInclude on temp table creation.

### ISSUE THREAD

**Issue by JonathanMyer** [PawelGerr/Thinktecture.EntityFrameworkCore#10]
I'm trying to create a temp table from a model with 100+ fields, but I only want to insert the primary keys into the temp table. Currently using 3.0.0-beta12 and the creation of the temp table uses all of the fields from the model instead of the ones I pass to the `SqlServerTempTableBulkInsertOptions.PropertiesToInsert`. So when it tries to do the insert, it fails because some of the fields are non-nullable, and the `PropertiesToInsert` option only inserts the specified fields.

From what I can tell in the `BulkInsertIntoTempTableAsync` function, the `tempTableOptions` is created from the `ISqlServerTempTableBulkInsertOptions.TempTableCreationOptions` which is a new set of options. I would like the `PropertiesToInsert` to pass from the `SqlServerTempTableBulkInsertOptions.PropertiesToInsert` to the `SqlServerTempTableCreationOptions.PropertiesToInclude` that way the temp table is only created with the fields specified in the `SqlServerTempTableBulkInsertOptions.PropertiesToInsert`.

Here is my function.
```
private async Task<IEnumerable<T>> GetExistingRecords<T>(IList<T> models) where T : BaseEntity<T>
{
    var options = new SqlServerTempTableBulkInsertOptions();
    var props = typeof(T).GetProperties()
        .Where(p => p.IsDefined(typeof(PrimaryKeyAttribute)) || p.IsDefined(typeof(IdentityAttribute)))
        .ToList();
    options.PropertiesToInsert = new EntityPropertiesProvider(props);
    var tempTable = await _dbContext.BulkInsertIntoTempTableAsync<T>(models.ToList(), options);
    var existing = await _dbContext.Set<T>()
        .Join(tempTable.Query,
        models.FirstOrDefault().GetPrimaryKeys,
        models.FirstOrDefault().GetPrimaryKeys,
        (x, y) => x)
        .ToListAsync();
    return existing;
}
```

I got it to work by changing line 302 of `SqlServerBulkOperationExecutor.cs` to 
```
tempTableOptions = new SqlServerTempTableCreationOptions(tempTableOptions) { PrimaryKeyCreation = PrimaryKeyPropertiesProviders.None, PropertiesToInclude = options.PropertiesToInsert };
```

This was working on 3.0.0-beta07 before `MembersToInsert` was changed to `PropertiesToInsert`. Perhaps there is another way to accomplish this that I'm not seeing?

**Comment by PawelGerr** [comment]
@JonathanMyer: I want you to know that the requested behavior will be "hidden" behind the flag "UsePropertiesToInsertForTempTableCreation" in the next version.

```csharp
var options = new SqlServerTempTableBulkInsertOptions
                    {
                       PropertiesToInsert = EntityPropertiesProvider.From<User>(u => u.Id),
                       Advanced =
                       {
                          UsePropertiesToInsertForTempTableCreation = true
                       }
                    };
```
