### ISSUE TITLE
Cannot resolve the collation conflict

### ISSUE THREAD

**Issue by totesz09** [PawelGerr/Thinktecture.EntityFrameworkCore#11]
Hey @PawelGerr!

We are facing with this problem in our project see in title, or the error message below.

```
cannot resolve the collation conflict between "sql_latin1_general_cp1_ci_as" and "hungarian_ci_as" in the equal to operation.
```

Our database in MSSQL created with: hungarian_ci_as COLLATE. 

Can we somewhere set the COLLATE or it is default?

**Comment by PawelGerr** [comment]
Hi, is it about temp tables?

If yes, then you can try setting the `UseDefaultDatabaseCollation` to `true`, so the string-columns are flagged with `COLLATE database_default`

```
var options = new SqlServerTempTableBulkInsertOptions{ UseDefaultDatabaseCollation = true };

await using var tempTableQuery = await ctx.BulkInsertValuesIntoTempTableAsync(data, options);
```

If the issue is not solved then I need more information, so I can reproduce the issue.

**Comment by totesz09** [comment]
Thanks for the, but i'm on the latest stable version which is 2.0.0 where I doesn't see this kind of option value.

**Comment by totesz09** [comment]
And we have some other restriction e.g.:

.core 3.1 because of LTS so the beta versions are doesn't good either for us. Can you recommend some workaround?

**Comment by PawelGerr** [comment]
The only workaround I can think of is to get the source code and make the necessary adjustments yourself.
The following commit might be of help to you: https://dev.azure.com/pawelgerr/Thinktecture.EntityFrameworkCore/_git/Thinktecture.EntityFrameworkCore/commit/d4b3ee2a495b66499b67447f9d064baa8a8fc5df?refName=refs%2Fheads%2Fmaster

**Comment by totesz09** [comment]
Thx for the answer and the help too!
