### ISSUE TITLE
Conflict with temporal tables

### ISSUE THREAD

**Issue by tbd-develop** [PawelGerr/Thinktecture.EntityFrameworkCore#16]
I'm using Temporal Tables along with the Bulk Insert operations on temp tables, and after testing an upgrade to EF Core 6.0 I'm experiencing an issue. 

Unhandled expression '[Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.TemporalAsOfTableExpression]' of type 'Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.TemporalAsOfTableExpression' encountered in 'SqlNullabilityProcessor'."

This occurs even if we remove the temp table from this particular query, as it appears that the Thinktecture SqlNullabilityProcessor is still part of the request. A bit of research suggests that they made some breaking changes around the SqlNullabilityProcessor in EF Core 6.0. I have updated to the latest beta4 to verify this is still a problem.

If I can provide any more information, please let me know.

**Comment by PawelGerr** [comment]
Hi, pls update the nuget package(s) to `4.0.0-beta05`.

**Comment by tbd-develop** [comment]
Thank you for such a quick fix! That seems to be working just fine now.
