### ISSUE TITLE
Bug in SqliteTempTableCreator Version 2.0.0

### ISSUE THREAD

**Issue by pscheicher** [PawelGerr/Thinktecture.EntityFrameworkCore#18]
Hi,

i encountered an error in the temptable creation using Thinktecture.EntityFrameworkCore.Sqlite v 2.0.0

The bug seems to be a missing whitespace here:
https://dev.azure.com/pawelgerr/_git/Thinktecture.EntityFrameworkCore?path=/src/Thinktecture.EntityFrameworkCore.Sqlite/EntityFrameworkCore/TempTables/SqliteTempTableCreator.cs&version=GBreleases/2.x.x&line=111&lineEnd=111&lineStartColumn=16&lineEndColumn=43&lineStyle=plain&_a=contents

ErrorMessage:
`Microsoft.Data.Sqlite.SqliteException: SQLite Error 1: 'near "NULLAUTOINCREMENT": syntax error'.`

StackTrace:
```
SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
    SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
    SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
    SqliteDataReader.NextResult()
    SqliteCommand.ExecuteReader(CommandBehavior behavior)
    SqliteCommand.ExecuteReader()
    SqliteCommand.ExecuteNonQuery()
    DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
    --- End of stack trace from previous location where exception was thrown ---
    RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
    RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
    RelationalCommand.ExecuteNonQueryAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
    RelationalDatabaseFacadeExtensions.ExecuteSqlRawAsync(DatabaseFacade databaseFacade, String sql, IEnumerable`1 parameters, CancellationToken cancellationToken)
    SqliteTempTableCreator.CreateTempTableAsync(IEntityType entityType, ITempTableCreationOptions options, CancellationToken cancellationToken)
    SqliteTempTableCreator.CreateTempTableAsync(IEntityType entityType, ITempTableCreationOptions options, CancellationToken cancellationToken)
```

Thank you for this library :)

**Comment by PawelGerr** [comment]
Hi, I remeber fixing this bug in the newer versions 1 or 2 years ago, but not in the `2.x.x`.
Please update the nuget package to `2.1.0` and try again.

**Comment by pscheicher** [comment]
Thank you for your quick response and the fix.
It resolves that issue, but leads to another error in creating the temp table:
`Microsoft.Data.Sqlite.SqliteException: SQLite Error 1: 'near "AUTOINCREMENT": syntax error'.`

I guess the `AUTOINCREMENT` keyword should only be added after the `PRIMARY KEY` and only for int columns. (https://www.sqlite.org/autoinc.html).

Unfortunately I cannot use a keyless temp table in my scenario - therefore I added an `int ID` property to my entity.
Using `[Key, DatabaseGenerated(DatabaseGeneratedOption.None)]` on this property creates the temp table, but gives me an identity problem on inserting.
For the moment I use as a workaround a `Guid ID { get; set; } = Guid.NewGuid()` which seems like a quite heavy workload in comparison to an autoincrement int.

**Comment by PawelGerr** [comment]
That's true, the `AUTOINCREMENT` is valid for PK of type `int` only.
I've backported the corresponding code from `4.x.x` and tested it with the following setup.

```csharp
   public class DemoDbContext : DbContext
   {
      protected override void OnModelCreating(ModelBuilder modelBuilder)
      {
         modelBuilder.ConfigureTempTableEntity<MyTempTable>(false);
      }
   }

   public class MyTempTable
   {
      [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
      public int Id { get; set; }

      public string SomeProperty { get; set; }
   }

//------------

await using var tempTable = await ctx.BulkInsertIntoTempTableAsync(new[]
                                                                   {
                                                                      new MyTempTable { SomeProperty = "Foo 1" },
                                                                      new MyTempTable { SomeProperty = "Foo 2" }
                                                                   });

var loadedEntities = await tempTable.Query.ToListAsync();
```

Looking good:
![image](https://user-images.githubusercontent.com/7135790/151633181-8ad9cd74-3011-46c6-b8f8-1aa4a81c402c.png)

The CI pipeline is finished, the packages v2.1.1 should be available in a few minutes.

PS: no chance to switch to EF Core 6 or at elast EF Core 5? :-)

**Comment by pscheicher** [comment]
Thank you, version `2.1.1` fixes my problem.

Yeah I've an update to EF Core 6 in the making, but need some speedup in querying and updating in my current production release. I'm looking forward to use Version `4.x.x` of your library :)
