### ISSUE TITLE
.Net 7

### ISSUE THREAD

**Issue by virzak** [PawelGerr/Thinktecture.EntityFrameworkCore#24]
Hi,

I'm starting to test my project with .Net 7 since it has some key fixes in the framework. The project depends on this library, so it cannot be upgraded without it.

Could you make a beta for .Net 7 or multitarget to both .net 6 and 7?

I did this for my library, so I'd be happy to send contributions as well.

https://github.com/zompinc/efcore-extensions/blob/087e3683c3fcaf02f9f3460cc809ef6dbf965e1e/src/Zomp.EFCore.WindowFunctions.SqlServer/Query/Internal/WindowFunctionsSqlServerQuerySqlGeneratorFactory.cs#L35-L41

**Comment by PawelGerr** [comment]
Are you talking about EF Core 6 or EF Core 7?
Current version, which references EF Core 6, should run on .NET 6 and .NET 7.
If you are talking about EF Core 7, then I released a new version `7.0.0-beta01`

**Comment by virzak** [comment]
I just realized that I could have stayed with EF Core 6, but thank you anyways.

**Comment by virzak** [comment]
@PawelGerr Could you update for RC.1 please?

The error is:

```
System.TypeLoadException : Method 'VisitDelete' in type 'Thinktecture.EntityFrameworkCore.Query.RelationalOptimizingVisitor' from assembly 'Thinktecture.EntityFrameworkCore.Relational, Version=7.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

**Comment by PawelGerr** [comment]
7.0.0-beta02 is released
