### ISSUE TITLE
Losing deviated data on abstract DbSet

### ISSUE THREAD

**Issue by endeffects** [PawelGerr/Thinktecture.EntityFrameworkCore#33]
Hallo,

I have an abstract DbSet and a couple of deviated entities using this base class.
I had to define a custom Discriminator to get this work and i'm also using shared columns here.

Everytime i'm using your BulkInsert(OrUpdate) extensions i'm losing all properties
of the deviated types and there columns are containing null only.

When i'm using AddRange or Update from the EF libraries everything works slowly fine.
Is there any chance that this can get fixed on your package?

My Specs: net Core 7.x, EF 7.x, Thinktecture 7.x Beta on Sql Server 

Regards

**Comment by PawelGerr** [comment]
As I understand, you are using [TPH](https://learn.microsoft.com/en-us/ef/core/modeling/inheritance#table-per-hierarchy-and-discriminator-configuration) in your project.
The library does not support any kind of inheritance (yet) but you can check out the [workaround](https://github.com/PawelGerr/Thinktecture.EntityFrameworkCore/commit/3244ac0d503b8de4efddaea5c589a33fa9ced9f4).
The method `BulkInsertHierarchyAsync` groups the entities by type and inserts the groups separately.

I will look into this in the following weeks. Maybe the workoround is the way to go, it just needs a bit polishing.
