### ISSUE TITLE
TempTable insert from query, not from values

### ISSUE THREAD

**Issue by codenessah** [PawelGerr/Thinktecture.EntityFrameworkCore#36]
Hi everyone,

is there a way to insert data in a temptable from a query. That would be faster than loading the values first in memory.

Normally you do this:

```
var _rowids = await _context.MyTable.Where( ... ).Select(c => c.rowid).ToListAsync();
var _temp = await _context.BulkInsertValuesIntoTempTableAsync(_rowids);
```

It would be nice to have something like this:

```
var _rowids = _context.MyTable.Where( ... ).Select(c => c.rowid);
var _temp = await _context.BulkInsertValuesIntoTempTableAsync(_rowids.ToQueryString());

```
Or is there already a way to do this?

LG codenessah

**Comment by PawelGerr** [comment]
Sorry, there is no such feature.

**Comment by codenessah** [comment]
Thanx Pawel,

as a workaround to get it go you can use something like this:

```
var _rowids = new List<Guid>() {Guid.Empty};
var _temp = await _context.BulkInsertValuesIntoTempTableAsync(_rowids); // just one Guid!

// then take the query string from above example
string _sSqlInsert = "delete from [" + _temp.Name + "]; insert into [" + _temp.Name + "] (Column1) " + _rowids.ToQueryString() + ";";
await _context.Database.ExecuteSqlRawAsync(_sSql);

// after that you can use ...
IQueryable<Guid> _queryTemp = _temp.Query;

```

LG codenessah

**Comment by PawelGerr** [comment]
Yes :)
Alternative way to create an empty temp table is to use `ITempTableCreator/ISqlServerTempTableCreator`.

```csharp
var tempTableCreator = _context.GetService<ISqlServerTempTableCreator>();
var tempTableReference = await tempTableCreator.CreateTempTableAsync(entityType, tempTableCreationOptions, cancellationToken).ConfigureAwait(false);
```

Example: [SqlServerBulkOperationExecutor.cs](https://dev.azure.com/pawelgerr/_git/Thinktecture.EntityFrameworkCore?path=/src/Thinktecture.EntityFrameworkCore.SqlServer/EntityFrameworkCore/BulkOperations/SqlServerBulkOperationExecutor.cs), lines 305-306
