### ISSUE TITLE
`IEntityPropertiesProvider.Exclude<T>` does not exclude properties for derived types

### ISSUE THREAD

**Issue by DavidAllardyce** [PawelGerr/Thinktecture.EntityFrameworkCore#37]
I have an entity which derives from another entity and when I attempt to do a Bulk Operation I cannot exclude properties because 
```csharp
 IEntityPropertiesProvider.Exclude<DerivedClass>(entity => new { entity.CreateDate });
``` 
does not remove the desired property from the property set.

I can replicate the issue with the following test using the test data:
```csharp
   var entityType = ActDbContext.Model.GetEntityType(typeof(TestEntityWithBaseClass));

   var optionalProperty = entityType.FindProperty(nameof(TestEntityWithBaseClass.Optional)) ?? throw new Exception("Property must not be null");
   var otherKeyProperty = entityType.FindProperty(nameof(TestEntityWithBaseClass.OtherKey)) ?? throw new Exception("Property must not be null");

    var propertiesProvider = IEntityPropertiesProvider.Exclude<TestEntityWithBaseClass>(entity => new
    {
        entity.Optional,
        entity.OtherKey
    });

    var properties = propertiesProvider.GetPropertiesForTempTable(entityType);
    properties.Should().HaveCount(entityType.GetProperties().Count() - 2);
    properties.Should().NotContain(optionalProperty);
    properties.Should().NotContain(otherKeyProperty);
```
It appears the issue is with the `Filter` method within `ExcludingEntityPropertiesProvider`. Specifically, `_members.All(m => m != p.Property.PropertyInfo && m != p.Property.FieldInfo)` does not match for the derived type.

If I change the `MemberInfo` comparison to something like this then my code works and all the tests pass:
```csharp
 member.MetadataToken == other.MetadataToken &&
 member.Module.Equals(other.Module) &&
 Equals(member.DeclaringType, other.DeclaringType)
```
(Okay, not all of the tests pass. The IfExists and IfNotExists fail, but they were failing before I made any changes)

I can submit a PR with my changes if you want to take a look.

**Comment by PawelGerr** [comment]
Thank your support! Please check out the version `4.5.1`/`7.0.0-beta05`.

**Comment by DavidAllardyce** [comment]
Excellent! That solved my problem. Thanks!
