### ISSUE TITLE
Method 'VisitAtTimeZone' does not have an implementation

### ISSUE THREAD

**Issue by uspwo** [PawelGerr/Thinktecture.EntityFrameworkCore#39]
Hi,

I am using currently using efcore 6.0.8 and this package in version 4.4.1 which works fine.
But when updating to efcore 7.0.3 on first query I got the following error.

System.TypeLoadException: "Method 'VisitAtTimeZone' in type 'Thinktecture.EntityFrameworkCore.Query.RelationalOptimizingVisitor' from assembly 'Thinktecture.EntityFrameworkCore.Relational, Version=4.4.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation."

**Comment by PawelGerr** [comment]
v4.x.x is for EF Core 6 only. Please use v7 for EF Core 7

**Comment by uspwo** [comment]
Thanks for your reply.
As I understand 4.5.1 is the latest version of this package
I cannot find a version 7 for EFCore 7. And as far as I know the EFCore 7 still doesn't support rownumbers.

**Comment by PawelGerr** [comment]
It is a prerelease https://www.nuget.org/packages/Thinktecture.EntityFrameworkCore.SqlServer/7.0.0-beta05

**Comment by uspwo** [comment]
Thank you
