### ISSUE TITLE
Query Hints?

### ISSUE THREAD

**Issue by JeffreyZolaVisibilEdi** [PawelGerr/Thinktecture.EntityFrameworkCore#43]
I have a query for which Optimizer has recommended Query Hints. Has this add-on only been configured to add Table Hints and not Query Hints? Is there a reason Query Hints are not configured?

**Comment by PawelGerr** [comment]
The query hints are not implemented because our customers didn't need them (yet).

**Comment by JeffreyZolaVisibilEdi** [comment]
Thank you for the response. 

I understand that your publicly available Nuget packages have been built as tools for your team to use for your clients' projects. That is a great marketing strategy, in my opinion!

In my use case, I have a query I have constructed in LINQ that queries out MSSQL database. A base query that joins a number of tables can be modified on a situation basis to add any of the half dozen or so search criteria. I found that one of them (a field representing the last name of the person to which each row of the response pertains) would take ~40 seconds to run from 
an ASP.NET Core MVC app in debug mode with Visual Studio 2022. When I captured the SQL, I saw it only took ~4 seconds to run the first time from SSMS, and then ~2 seconds for subsequent executions. I also found that if I use the "RECOMPILE" query hint, it would take the same ~40 seconds to execute.

I entered the query into an Optimizer, which suggested two query hints. I have not been able to test those query hints running the application yet, because I also observed that this is the only one of the potential search terms that doesn't perform well. 

I have not proved it yet, but my theory is that something with how I have the DbContext configured is preventing the database from using cached query plans. Do you have any suggestions?

Thanks in advance!
Jeff Zola

**Comment by PawelGerr** [comment]
It sounds like your query has multiple JOINs. If some of them have the cardinality 1-N or M-N then try out [`AsSplitQuery()`](https://learn.microsoft.com/en-us/ef/core/querying/single-split-queries#split-queries).

**Comment by JeffreyZolaVisibilEdi** [comment]
I tried this, as well as AsSingleQuery(). No change at all.  The database appears to be using the same query plan for all instances.

I took the time this morning to look at the query plan used when the query is run by SSMS and EFCore. The OPPOSITE of what I expected is happening. SSMS reuses a query plan if I use the same parameters. EFCore ALWAYS uses the same query plan. But the query plans are different.

**Comment by PawelGerr** [comment]
From your description I think that the query is to complex and need some "restructuring", but I cannot say anything specific without analysing it.
A query hint could easy up the problem a little, but I don't think it solves the issue entirely.
