### ISSUE TITLE
EF Core Relationships

### ISSUE THREAD

**Issue by Math-rm1** [PawelGerr/Thinktecture.EntityFrameworkCore#50]
Hey,

I'm currently using this library for bulk operations in my .NET 8.0 project. The bulk upsert method works well for parent entities, but it doesn't seem to handle cascading updates on related entities. Is there support for this feature, or any advice on achieving it with the current version?

Thanks!

**Comment by PawelGerr** [comment]
Are you talking about [owned entities](https://learn.microsoft.com/en-us/ef/core/modeling/owned-entities)? If not then you have to make bulk-update twice, one call for parents and one call for children.

```csharp
List<Parent> parents = ...;
List<Child> children = parents.Select(p => p.Child).ToList();

await ctx.BulkUpdateAsync(parents);
await ctx.BulkUpdateAsync(children);
```
