### ISSUE TITLE
Invalid object name #Temp{Entity}

### ISSUE THREAD

**Issue by symbarh** [PawelGerr/Thinktecture.EntityFrameworkCore#57]
BulkInsertIntoTempTableAsync creates a temp table named #Temp{Entity}_1, but the query is referencing #Temp{Entity}

**Comment by PawelGerr** [comment]
Could you please provide a small repro?

**Comment by symbarh** [comment]
I found a workaround; I implemented a custom `ITempTableNameProvider` and a `ITempTableNameLease` to return a temporary table name without the integer suffix. I will provide a reproducible code when I find the time. Thank you.
